# 端口
server:
  port: 18761

spring:
  application:
    name: eureka-server

# Eureka配置
eureka:
  instance:
    # eureka服务端的实例名称
    hostname: localhost
    # 访问路径可以显示IP地址
    prefer-ip-address: true
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检查服务
    fetch-registry: false
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.server.port:18761}/eureka/
      # 集群模式：设置服务注册中心地址，指向其他注册中心
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka8762.com:8762/eureka,http://${spring.security.user.name}:${spring.security.user.password}@eureka8763.com:8763/eureka
#  server:
#    # 是否开启自我保护模式，默认是true
#    enable-self-preservation: false
#    # 剔除失效服务间隔。单位 毫秒。 默认值 60 * 1000
#    eviction-interval-timer-in-ms: 1000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true